description: Dummy LED strip for testing

compatible: "dummy,led-strip"

properties:
  chain-length:
    type: int
    required: true
    description: Number of LEDs in strip

  color-mapping:
    type: array
    required: true
    description: Color channel mapping

  "#led-cells":
    type: int
    const: 3
    description: Number of cells in LED specifier

  "#binding-cells":
    type: int
    const: 0
