---
include:
  - board: seeeduino_xiao_ble
    shield: takmak_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=4
    artifact-name: takmak_dongle
  - board: nice_nano_v2
    shield: takmak_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: takmak_left
  - board: nice_nano_v2
    shield: takmak_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: takmak_right
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: takmak_left_right_settings_reset
  - board: nice_nano_v2
    shield: takmak_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: takmak_left_central
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: takmak_dongle_settings_reset
