---
include:
  - board: seeeduino_xiao_ble
    shield: takmak_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=4
    artifact-name: dongle
  - board: nice_nano_v2
    shield: takmak_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: left
  - board: nice_nano_v2
    shield: takmak_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: right
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: left_right_reset
  - board: nice_nano_v2
    shield: takmak_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: left_central
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: dongle_reset
  - board: nice_nano_v2
    shield: takmak_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_KEYBOARD_NAME="Left"
    artifact-name: left_alt
  - board: nice_nano_v2
    shield: takmak_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_KEYBOARD_NAME="Right"
    artifact-name: right_alt
