---
include:
  - board: seeeduino_xiao_ble
    shield: takmak_dongle prospector_adapter
  - board: nice_nano_v2
    shield: takmak_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: takmak_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y`
  - board: nice_nano_v2
    shield: settings_reset