---
include:
  - board: seeeduino_xiao_ble
    shield: takmak_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: '-DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=4 -DCONFIG_ZMK_KEYBOARD_NAME="\"Takmak 3.1\""'
    artifact-name: dongle

  - board: nice_nano_v2
    shield: takmak_left
    snippet: studio-rpc-usb-uart
    cmake-args: "-DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_KEYBOARD_NAME='\"Takmak 3.1 L\"'"
    artifact-name: left
  - board: nice_nano_v2
    shield: takmak_right
    snippet: studio-rpc-usb-uart
    cmake-args: "-DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_KEYBOARD_NAME='\"Takmak 3.1 R\"'"
    artifact-name: right

  - board: nice_nano_v2
    shield: takmak_left
    snippet: studio-rpc-usb-uart
    cmake-args: "-DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_KEYBOARD_NAME='\"Takmak 3.1\"'"
    artifact-name: left_central

  - board: nice_nano_v2
    shield: takmak_left
    snippet: studio-rpc-usb-uart
    cmake-args: "-DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_KEYBOARD_NAME='\"Takmak 3.1 L2 \"'"
    artifact-name: left_alt
  - board: nice_nano_v2
    shield: takmak_right
    snippet: studio-rpc-usb-uart
    cmake-args: "-DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_KEYBOARD_NAME='\"Takmak 3.1 R2 \"'"
    artifact-name: right_alt

  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: left_right_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: dongle_reset
