---
include:
  - board: seeeduino_xiao_ble
    shield: takmak_dongle dongle_screen
    snippet: studio-rpc-usb-uart
    cmake-args: '-DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2 -DCONFIG_ZMK_KEYBOARD_NAME="\"Takmak 3.1 D\""'
    artifact-name: dongle

  - board: nice_nano_v2
    shield: takmak_left
    snippet: studio-rpc-usb-uart
    cmake-args: '-DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_KEYBOARD_NAME=''"Takmak 3.1 L"'''
    artifact-name: dongle_left
  - board: nice_nano_v2
    shield: takmak_right
    snippet: studio-rpc-usb-uart
    cmake-args: '-DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_KEYBOARD_NAME=''"Takmak 3.1 R"'''
    artifact-name: dongle_right

  - board: nice_nano_v2
    shield: takmak_left
    snippet: studio-rpc-usb-uart
    cmake-args: '-DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_KEYBOARD_NAME=''"Takmak 3.1 SL"'''
    artifact-name: standalone_left_central
  - board: nice_nano_v2
    shield: takmak_right
    snippet: studio-rpc-usb-uart
    cmake-args: '-DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_KEYBOARD_NAME=''"Takmak 3.1 SR"'''
    artifact-name: standalone_right

  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: reset_keyboard
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: reset_dongle
