manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: seniorsoftwarevlogger
      url-base: https://github.com/seniorsoftwarevlogger
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 147c340c6e8d377304acfdd64dc86cf83ebdfef2 # (see important notice in Installation Guide in the dongle-screen readme)
      import: app/west.yml
    - name: zmk-dongle-screen
      remote: seniorsoftwarevlogger
      revision: cea154a53e3f791d769666aebd719cbe4a479391
  self:
    path: config
