manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: seniorsoftwarevlogger
      url-base: https://github.com/seniorsoftwarevlogger
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-dongle-screen
      remote: seniorsoftwarevlogger
      revision: main
  self:
    path: config
